### PR TITLE
make install

### PR DESCRIPTION
**Pull request by HadrienG**
Hi, I'm a contributor for the Homebrew package manager and we're in the process of updating and curating the build process of a lot of packages.

Mothur currently doesn't have a `make install` step, which makes it harder to ship and package in a standard way.

This pull request adds an `install` rule in the `Makefile`

`make install` would now install `mothur` and `uchime` in `/usr/local/bin` by default.
`make install PREFIX=/path/here` would allow the user to specify a custom location.

Best,
Hadrien

### CODE REVIEW

**Comment by HadrienG** [comment]
This seems to break your CI.

If you are positive going forward with this PR I'm happy to either modify `.travis.yml` with `./mothur` instead of the old `make install` or opening another PR with a `make; make install` and some kind of test

**Comment by mothur-westcott** [comment]
I like the idea.  By default it would be nice to leave the executable where it is, but allow for setting an install location so that the change would be transparent to users not looking to move the executable.  This should also resolve the CI issue.

**Comment by HadrienG** [comment]
I modified the PR according to your suggestions. `make install` should now leave the executables where they are by default and accept a `PREFIX` option for users who wish to move them.

**Comment by mothur-westcott** [comment]
👍 , thanks for contributing!

**Comment by HadrienG** [comment]
Thank you for merging this! 
Any chance you'd release a minor release or this will be in `1.40`?

**Comment by ilovezfs** [comment]
The `PREFIX` should really be the parent directory, with the executable itself getting installed into PREFIX/bin.

If you're setting the bin directory itself, the variable is usually named BINDIR not PREFIX.

**Comment by ilovezfs** [comment]
Here is an example: https://github.com/micropython/micropython/blob/master/ports/unix/Makefile#L196-L197

**Comment by ilovezfs** [comment]
Also
https://github.com/jordansissel/grok/blob/master/Makefile#L9
https://github.com/jordansissel/grok/blob/master/Makefile#L94

**Comment by ilovezfs** [comment]
And
https://github.com/zpaq/zpaq/blob/master/Makefile#L5-L6
https://github.com/zpaq/zpaq/blob/master/Makefile#L24-L25

Anyway, let me know if you need more examples.

**Comment by mothur-westcott** [comment]
f1c0c9f781a0c3d2c451deae570cb3e0e27e2c67

**Comment by HadrienG** [comment]
thank you @mothur-westcott !

**Pull request merged**
